### ISSUE TITLE
node / npm removed on reactredux project

### ISSUE THREAD

**Issue by timriker** [cloudfoundry/dotnet-core-buildpack#172] opened 2017-10-20 21:40 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
api version 2.94.0
cli 6.32.0+0191c33d9.2017-09-26

What version of the buildpack you are using?
1.0.29 from github

If you were attempting to accomplish a task, what was it you were attempting to do?
deploy sample dotnet reactredux application

What did you expect to happen?
app would do server side rendering

What was the actual behavior?
node / npm were removed before application started causing error message

Please confirm where necessary:
* [ ] I have included a log output
* [X ] My log includes an error message
* [X ] I have included steps for reproduction

In an empty directory:
$ dotnet new reactredux
$ npm install
$ cf push reactredux -b https://github.com/cloudfoundry/dotnet-core-buildpack.git

Web error:
"An error occurred while processing your request."

CF logs error:
"An unhandled exception has occurred: Failed to start Node process."

adding INSTALL_NODE: true in a manifest does work around the issue.

Note: doing a `dotnet publish` and then running the `cf push` from the publish directory reduces the number of files deployed, but still gets the same errors.

**Comment by kardolus** [comment] 2018-12-12 15:16
No worries. Closing the issue because we are not able to reproduce this.

**Comment by sclevine** [comment] 2018-12-12 21:17
This is a feature request -- currently the buildpack always removes node at launch unless `INSTALL_NODE=true`. The buildpack should detect when node is needed at launch and keep node around in the droplet.

**Comment by Zanadar** [comment] 2019-02-04 16:03
@sclevine The default app created by `dotnet new reactredux` does not use server side rendering, and thus this feature request doesn't line up with the issue, as far as I can tell.

**Comment by timriker** [comment] 2019-02-04 16:45
react/redux has server side rendering as a core feature. Rendering pages for search engine consumption should be well supported. Why, @Zanadar, do you feel this does not line up?

Doing a `dotnet new reactredux` should result is a usable deploy, no? It didn't at the time I opened this issue.

**Comment by Zanadar** [comment] 2019-02-04 17:14
Sorry I wasn't clear. I totally agree server side rendering is an important feature and we should support it. 
There seem to be a few issues:
1. Does `dotnet new reactredux` run by default in the buildpack?
2. Does the buildpack support server-side rendering?
1. Do we build in logic to detect the use of server side rendering for react apps and package the node binary for these cases?

For 1, the current version works. See below:
For 2, the user can use `INSTALL_NODE=true` to get node in their droplet.
For 3, it's certainly a possibility and we'll look into prioritizing.

![screen shot 2019-02-04 at 12 12 55 pm](https://user-images.githubusercontent.com/5925347/52224537-3ca1cf00-2876-11e9-904e-3e308710f5dd.png)

**Comment by Zanadar** [comment] 2019-02-22 16:54
Closing as covered VIA documentation.

**Closed by Zanadar** 2019-02-22 16:54 UTC
Labels: accepted, enhancement
