### ISSUE TITLE
runtimeconfig.json error in version 1.0.7

### ISSUE THREAD

**Issue by emailtowalter** [cloudfoundry/dotnet-core-buildpack#128] opened 2016-12-21 19:41 UTC
Hi ... when CF push using version 1.0.7, we saw the following error. We are using .NET core 1.1. It worked fine with version 1.0.6.  We use Self-Contained approach and published the binary as suggested. 

Globla.json 
...
  "sdk": {
    "version": "1.0.0-preview2-1-003177"
  }

...runtimeconfig.json from publish folder:
{
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  }
}

Error:
"
ASP.NET Core buildpack version: 1.0.7
ASP.NET Core buildpack starting compile
-----> Restoring files from buildpack cache
       Copied 38 files from /tmp/cache/libunwind to /tmp/staged/app
       OK
-----> Restoring NuGet packages cache
       OK
-----> Installing .NET Core runtime(s)
       FAILED: Could not get version from /tmp/staged/app/{myappname}.runtim
econfig.json
       FAILED: Installing .NET Core runtime(s) failed, Could not get version fro
m /tmp/staged/app/{myappname}.runtimeconfig.json
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed
"

**Comment by degrim** [comment] 2016-12-21 19:53
@emailtowalter Can you provide the contents of the runtimeconfig.json file (should be named something like `<project_name>.runtimeconfig.json` in the publish output folder)?  Also, which tooling versions are you using (`1.0.0-preview2-1-003177` or `1.0.0-preview3-004056`)?  Was the project published from VS (2015 or 2017?) or from the command-line with `dotnet publish`?

**Comment by emailtowalter** [comment] 2016-12-21 19:55
hi degrim... just updated the original post. WE use command-line to publish.

**Comment by degrim** [comment] 2016-12-21 19:58
@emailtowalter Thanks, can you provide the `project.json` file as well?  For some reason the runtime version isn't specified in the `runtimeconfig.json` file here.

/cc
@sesmith177 @RochesterinNYC 
This seems similar to #123 but uses the project.json tooling instead of msbuild.

**Comment by emailtowalter** [comment] 2016-12-21 20:01
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Configuration": "1.1.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "System.Xml.XmlDocument": "4.0.1",
....
  },


  "tools": {
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "copyToOutput": {
      "include": [
        "**.cshtml",
        "wwwroot",
        "key-*.xml",
        "*.pfx",
        "appsettings*.json",
        "Tables"
      ],
      "exclude": [ "bin", "obj" ]
    },
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "**.cshtml",
      "wwwroot",
      "web.config",
      "key-*.xml",
      "*.pfx",
      "appsettings*.json",
      "Tables",
      "../../*.yml"
    ],
    "exclude": [ "bin", "obj", "publish"]
  },

  "scripts": {
    "postpublish": []
  },

  "runtimes": {
    "win7-x64": {},
    "win10-x64": {},
    "osx.10.10-x64": {},
    "ubuntu.14.04-x64": {}
  }

}

**Comment by degrim** [comment] 2016-12-21 20:10
@sesmith177 It looks like the buildpack is always trying to install .NET Core runtimes [here](https://github.com/cloudfoundry/dotnet-core-buildpack/blob/master/lib/buildpack/compile/compiler.rb#L56), but this isn't required when pushing a self-contained application.  We should change this to detect if the application is self-contained (contains the runtime with it) and skip this step in that case.

**Comment by emailtowalter** [comment] 2016-12-21 20:16
good to know. do you know how soon we can have the fix? is it possible to switch back to 1.0.6? Thanks

**Comment by degrim** [comment] 2016-12-21 20:21
@emailtowalter You should be able to use the `v1.0.6` tag when specifying the buildpack.

For example:
`cf push <app_name> -b https://github.com/cloudfoundry/dotnet-core-buildpack.git#v1.0.6`

**Comment by sesmith177** [comment] 2016-12-22 18:42
We have fixed this on develop with commit: 5bebb973376f63dba4133a5dbafaa87f03213ff1

This commit includes a fixture app to prevent this regression in the future.

**Comment by degrim** [comment] 2016-12-29 15:39
@emailtowalter Can you confirm that the new release (v1.0.8) resolves this issue?

**Comment by emailtowalter** [comment] 2016-12-29 21:00
Probably not going to be done in 2 weeks. On vacation.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: Daniel GrimSent: Thursday, December 29, 2016 10:39 AMTo: cloudfoundry/dotnet-core-buildpackReply To: cloudfoundry/dotnet-core-buildpackCc: emailtowalter; MentionSubject: Re: [cloudfoundry/dotnet-core-buildpack] runtimeconfig.json error in version 1.0.7 (#128)@emailtowalter Can you confirm that the new release (v1.0.8) resolves this issue?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cloudfoundry/dotnet-core-buildpack","title":"cloudfoundry/dotnet-core-buildpack","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cloudfoundry/dotnet-core-buildpack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@degrim in #128: @emailtowalter Can you confirm that the new release (v1.0.8) resolves this issue?"}],"action":{"name":"View Issue","url":"https://github.com/cloudfoundry/dotnet-core-buildpack/issues/128#issuecomment-269647477"}}}

**Comment by dgodd** [comment] 2017-01-17 15:23
@emailtowalter I hope you had a nice holiday, assuming you are now back at work, could you confirm that this problem is now fixed?

**Comment by emailtowalter** [comment] 2017-01-17 17:10
It is fixed in version 1.0.9, since that is the version we are using. Thanks for the follow-up.Walter                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: Dave GoddardSent: Tuesday, January 17, 2017 10:23 AMTo: cloudfoundry/dotnet-core-buildpackReply To: cloudfoundry/dotnet-core-buildpackCc: emailtowalter; MentionSubject: Re: [cloudfoundry/dotnet-core-buildpack] runtimeconfig.json error in version 1.0.7 (#128)@emailtowalter I hope you had a nice holiday, assuming you are now back at work, could you confirm that this problem is now fixed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cloudfoundry/dotnet-core-buildpack","title":"cloudfoundry/dotnet-core-buildpack","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cloudfoundry/dotnet-core-buildpack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dgodd in #128: @emailtowalter I hope you had a nice holiday, assuming you are now back at work, could you confirm that this problem is now fixed?"}],"action":{"name":"View Issue","url":"https://github.com/cloudfoundry/dotnet-core-buildpack/issues/128#issuecomment-273199476"}}}

**Closed** 2017-01-23 15:13 UTC
Labels: accepted, bug
