### ISSUE TITLE
Portable applications published with MSBuild tooling do not work

### ISSUE THREAD

**Issue by degrim** [cloudfoundry/dotnet-core-buildpack#123] opened 2016-12-09 04:29 UTC
The preview3 tooling for MSBuild produces slightly different outputs than the preview2 tooling for project.json projects.  The previous tooling produced a .runtimeconfig.json file which the buildpack used to detect the framework version to install and use to run the application.  The preview3 tooling does not provide this file in the publish output, however, it does provide a .deps.json file which also provides information about the framework version to be used.  Since the preview2 tooling also provides this .deps.json file in the same format, I think we can probably make the change to use this file instead of the .runtimeconfig.json without depending on the other changes for the msbuild tooling to happen first.

@sesmith177 @RochesterinNYC Any thoughts on this?

**Comment by sesmith177** [comment] 2016-12-09 14:44
@degrim We just tried publishing an app using preview3 and the .runtimeconfig.json file was created. The command we ran:

```
dotnet publish asp_web_app.csproj --output /tmp/publish
```

The CLI version was preview3:

```
○ → dotnet --version
1.0.0-preview3-004056
```

I'll upload our asp_web_app.csproj

**Comment by degrim** [comment] 2016-12-09 15:37
@sesmith177 Odd, when I tried from VS2017 and from the command-line both versions did not include the .runtimeconfig.json file.

**Comment by athornton2012** [comment] 2016-12-14 15:57
@degrim are you still having this issue?

**Comment by degrim** [comment] 2016-12-14 16:08
@athornton2012 it was 1.0.0-preview3-004056, the version that is installed with VS 2017 RC.

**Comment by keaty** [comment] 2016-12-20 15:49
@degrim have you tried and seen this behavior since?

**Comment by degrim** [comment] 2016-12-20 16:07
@keaty I haven't had a chance to try with the latest VS2017 release yet.

**Comment by sesmith177** [comment] 2017-01-03 21:40
@degrim if you're still running into this problem, could we see the `*.csproj` to try to reproduce on our end?

**Comment by degrim** [comment] 2017-01-04 03:48
@sesmith177 See [here](https://github.com/degrim/aspnet-core-BluemixDeploySample/blob/VS2017/src/BluemixDeploySample/BluemixDeploySample.csproj) for the csproj file (also the rest of the project is there too).  The idea is that this should function similar to the VS2015 branch of that repository which uses the project.json tooling and should publish the application to CF after the build completes (assuming you've already logged in and targeted an org/space).

**Comment by sesmith177** [comment] 2017-01-04 17:05
@degrim I think it has something to do with the `runtimeconfig.template.json` file as including it in the app causes the *.runtimeconfig.json file not to be included. 

This issue: https://github.com/dotnet/sdk/issues/471 looks like it may be interesting

**Comment by sesmith177** [comment] 2017-01-10 17:13
@degrim Since it looks like this is a .NET SDK bug, I think we should probably close this issue

**Comment by degrim** [comment] 2017-01-10 22:35
@sesmith177 The issue that you referenced is closed, but the latest nightly build of the .NET CLI (`1.0.0-preview5-004456`) produces the same output.  I think this may be the intended behavior of the CLI.

**Comment by sclevine** [comment] 2017-01-17 20:45
@degrim I'm unclear if there's something actionable here. Do we make a change in the buildpack?

**Comment by degrim** [comment] 2017-01-17 20:51
@sclevine Currently, the buildpack will fail for projects which include a `runtimeconfig.template.json` file, as @sesmith177 mentioned above, so we need to decide if we should wait and see if that will change or rely on the `*.deps.json` file instead of `*.runtimeconfig.json`.

**Comment by sesmith177** [comment] 2017-01-23 15:50
@sclevine we agree that we should make the change to use `*.deps.json` instead of `*.runtimeconfig.json` for detecting whether an app is pubished or not, and for determining the framework version to install for published apps

**Comment by sclevine** [comment] 2017-01-23 16:44
Story to make this change: https://www.pivotaltracker.com/story/show/138161349

**Comment by sesmith177** [comment] 2017-01-26 18:29
After further investigation:

1. The `*.runtimeconfig.json` file is both expected output and necessary for .NET Core apps to run

2. The issue https://github.com/dotnet/sdk/issues/471 has been fixed; the latest version of the .NET CLI will correctly generate a `*.runtimeconfig.json` file when a `runtimeconfig.template.json` file is present.

3. This [app](https://github.com/degrim/aspnet-core-BluemixDeploySample/blob/VS2017/src/BluemixDeploySample/BluemixDeploySample.csproj) was failing to generate a `*.runtimeconfig.json` file because it was missing the `<OutputType>Exe</OutputType>` tag in its `csproj` file.

Closing

**Closed by sesmith177** 2017-01-26 18:29 UTC
Labels: enhancement, unscheduled
