### ISSUE TITLE
Application failed to deploy

### ISSUE THREAD

**Issue by CleverChuk** [cloudfoundry/dotnet-core-buildpack#190] opened 2018-07-02 15:04 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
6.34.1

What version of the buildpack you are using?
1.0.5

If you were attempting to accomplish a task, what was it you were attempting to do?
deploy [this](https://github.com/IBM-Cloud/aspnet-core-helloworld) application

What did you expect to happen?
Successful deployment of the application without errors

What was the actual behavior?
Failed to deploy

```
 Download [https://buildpacks.cloudfoundry.org/dependencies/dotnet-framework/dotnet-framework.1.0.5.linux-amd64-1251a036.tar.xz]
          **WARNING** A newer version of dotnet-framework is available in this buildpack. Please adjust your app to use version 1.0.11 instead of version 1.0.5 as soonas possible. Old versions of dotnet-framework are only provided to assist in migrating to newer versions.
   -----> Installing dotnet-framework 1.1.0
          **ERROR** DEPENDENCY MISSING IN MANIFEST:

          Version 1.1.0 of dependency dotnet-framework is not supported by this buildpack.
          The versions of dotnet-framework supported in this buildpack are:
                - 1.0.5
                - 1.0.11
                - 1.1.2
                - 1.1.8
                - 2.0.0
                - 2.0.7
                - 2.1.0
                - 2.1.1

          **ERROR** Unable to install required dotnet frameworks: dependency dotnet-framework 1.1.0 not found
   Failed to compile droplet: Failed to run finalize script: exit status 12
   Exit status 223
   Cell 1fa108f8-8af5-40d8-80ec-c02762bd3e48 stopping instance c4273ea8-0239-46aa-94f8-01f6704e600b
   Cell 1fa108f8-8af5-40d8-80ec-c02762bd3e48 destroying container for instance c4273ea8-0239-46aa-94f8-01f6704e600b
Error staging application: App staging failed in the buildpack compile phase
FAILED
```
=============
To reproduce the error clone the repo
cd into aspnet-core-helloworld
cf push
======
updated the version in the *.csproj file to 1.0.11 and it still did not deploy.
Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by astrieanna** [comment] 2018-07-09 17:45
Reproduced with buildpack version `2.1.3`.

The buildpack detects two required versions (`1.0.5` and `1.1.0`, even after changing that `*.csproj` to `1.0.11`):
```
Downloaded app package (26.2K)
   -----> Dotnet-Core Buildpack version 2.1.3.20180709121638
   -----> Supplying Dotnet Core
   -----> Installing libunwind 1.2.1
          Download [https://buildpacks.cloudfoundry.org/dependencies/libunwind/libunwind-1.2.1-4bc9ce84.tar.gz]
          using the default SDK
   -----> Installing dotnet 2.1.301
          Download [https://buildpacks.cloudfoundry.org/dependencies/dotnet/dotnet.2.1.301.linux-amd64-eb50d3ec.tar.xz]
   -----> Finalizing Dotnet Core
   -----> Restore dotnet dependencies
            Restoring packages for /tmp/app/src/WebApplication/WebApplication.csproj...
            Restoring packages for /tmp/app/src/WebApplication/WebApplication.csproj...
            Installing System.Xml.XPath 4.0.1.
            Installing runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.0.
            Installing runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing runtime.native.System.IO.Compression 4.3.0.
            Installing Microsoft.NETCore.Targets 1.1.0.
            Installing System.Text.Encoding.CodePages 4.0.1.
            Installing System.Xml.XmlDocument 4.0.1.
            Installing BundlerMinifier.Core 2.4.337.
            Installing NUglify 1.5.5.
            Installing Newtonsoft.Json 9.0.1.
            Installing Microsoft.CodeAnalysis.Analyzers 1.1.0.
            Installing Microsoft.NETCore.App 1.1.0.
            Installing NETStandard.Library 1.6.0.
            Installing System.Security.Cryptography.Algorithms 4.2.0.
            Installing System.Xml.XPath.XDocument 4.0.1.
            Installing System.Diagnostics.FileVersionInfo 4.0.0.
            Installing System.Collections 4.0.11.
            Installing System.Diagnostics.StackTrace 4.0.1.
            Installing Microsoft.NETCore.DotNetHost 1.1.0.
            Installing runtime.native.System.IO.Compression 4.1.0.
            Installing System.Security.Cryptography.Csp 4.0.0.
            Installing System.Diagnostics.Debug 4.0.11.
            Installing System.Security.Cryptography.Cng 4.2.0.
            Installing runtime.native.System.Net.Http 4.0.1.
            Installing System.Security.Cryptography.OpenSsl 4.0.0.
            Installing System.Globalization.Extensions 4.0.1.
            Installing System.Dynamic.Runtime 4.0.11.
            Installing System.Globalization 4.0.11.
            Installing System.Diagnostics.DiagnosticSource 4.0.0.
            Installing runtime.native.System 4.0.0.
            Installing System.Buffers 4.0.0.
            Installing System.Reflection.Emit.Lightweight 4.3.0.
            Installing System.Security.Cryptography.Cng 4.3.0.
            Installing System.IO 4.1.0.
            Installing System.Security.Cryptography.Csp 4.3.0.
            Installing System.Linq 4.1.0.
            Installing runtime.native.System.Net.Http 4.3.0.
            Installing runtime.native.System.Security.Cryptography.Apple 4.3.0.
            Installing System.Security.Principal 4.3.0.
            Installing System.Security.Cryptography.OpenSsl 4.3.0.
            Installing System.ObjectModel 4.0.12.
            Installing System.Security.Claims 4.3.0.
            Installing System.Reflection 4.1.0.
            Installing runtime.native.System.Net.Security 4.3.0.
            Installing runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
            Installing Microsoft.Win32.Registry 4.3.0.
            Installing System.Reflection.Extensions 4.0.1.
            Installing System.Threading.Overlapped 4.3.0.
            Installing System.Resources.ResourceManager 4.0.1.
            Installing System.Security.Principal.Windows 4.3.0.
            Installing System.Runtime 4.1.0.
            Installing System.Runtime.Extensions 4.1.0.
            Installing runtime.native.System 4.3.0.
            Installing System.Reflection.Emit 4.3.0.
            Installing System.Reflection.Emit.ILGeneration 4.3.0.
            Installing System.Runtime 4.3.0.
            Installing System.Runtime.Serialization.Primitives 4.1.1.
            Installing System.Text.Encoding 4.0.11.
            Installing System.Text.Encoding.Extensions 4.0.11.
            Installing System.Text.RegularExpressions 4.1.0.
            Installing System.Threading 4.0.11.
            Installing System.Threading.Tasks 4.0.11.
            Installing System.Xml.XDocument 4.0.11.
            Installing System.Linq.Expressions 4.1.0.
            Installing Microsoft.CSharp 4.0.1.
            Installing System.Xml.ReaderWriter 4.0.11.
            Installing Microsoft.DiaSymReader.Native 1.4.0.
            Installing Microsoft.NETCore.Runtime.CoreCLR 1.1.0.
            Installing Libuv 1.9.1.
            Installing Microsoft.NETCore.DotNetHostPolicy 1.1.0.
            Installing Microsoft.CodeAnalysis.CSharp 1.3.0.
            Installing Microsoft.CodeAnalysis.VisualBasic 1.3.0.
            Installing NETStandard.Library 1.6.1.
            Installing System.Buffers 4.3.0.
            Installing System.Linq.Queryable 4.3.0.
            Installing System.Net.WebHeaderCollection 4.3.0.
            Installing System.Security.Cryptography.Primitives 4.3.0.
            Installing System.Reflection.TypeExtensions 4.3.0.
            Installing System.Reflection.DispatchProxy 4.3.0.
            Installing System.Net.NameResolution 4.3.0.
            Installing System.IO.UnmanagedMemoryStream 4.3.0.
            Installing System.IO.FileSystem.Watcher 4.3.0.
            Installing System.Threading.Tasks.Parallel 4.3.0.
            Installing System.Globalization.Extensions 4.3.0.
            Installing System.ComponentModel 4.3.0.
            Installing System.Resources.Reader 4.3.0.
            Installing System.Dynamic.Runtime 4.3.0.
            Installing System.ComponentModel.Annotations 4.3.0.
            Installing System.Net.Requests 4.3.0.
            Installing System.Threading.Tasks.Extensions 4.3.0.
            Installing System.Threading.Thread 4.3.0.
            Installing System.Diagnostics.Process 4.3.0.
            Installing System.Threading.Tasks.Dataflow 4.7.0.
            Installing System.Runtime.Loader 4.3.0.
            Installing System.Linq.Parallel 4.3.0.
            Installing System.Numerics.Vectors 4.3.0.
            Installing System.Security.Cryptography.Encoding 4.3.0.
            Installing System.Threading.ThreadPool 4.3.0.
            Installing System.Diagnostics.DiagnosticSource 4.3.0.
            Installing Microsoft.CSharp 4.3.0.
            Installing System.Collections.Immutable 1.3.0.
            Installing System.IO.MemoryMappedFiles 4.3.0.
            Installing System.Reflection.Metadata 1.4.1.
            Installing System.Net.Security 4.3.0.
            Installing System.Security.Cryptography.Algorithms 4.3.0.
            Installing System.Security.Cryptography.X509Certificates 4.3.0.
            Installing System.Linq.Expressions 4.3.0.
            Installing System.Net.Http 4.3.0.
            Installing Microsoft.VisualBasic 10.1.0.
            Installing Microsoft.NETCore.Platforms 1.0.1.
            Installing Microsoft.Win32.Primitives 4.0.1.
            Installing System.AppContext 4.1.0.
            Installing System.Collections.Concurrent 4.0.12.
            Installing System.Console 4.0.0.
            Installing System.Diagnostics.Tools 4.0.1.
            Installing System.Globalization.Calendars 4.0.1.
            Installing System.Runtime.Extensions 4.3.0.
            Installing System.IO.Compression.ZipFile 4.0.1.
            Installing System.IO.FileSystem 4.0.1.
            Installing System.IO.FileSystem.Primitives 4.0.1.
            Installing System.Net.Sockets 4.1.0.
            Installing System.Runtime.Handles 4.0.1.
            Installing System.IO.Compression 4.3.0.
            Installing System.Runtime.InteropServices.RuntimeInformation 4.0.0.
            Installing System.Runtime.Numerics 4.0.1.
            Installing System.Security.Cryptography.Encoding 4.0.0.
            Installing System.Threading.Tasks 4.3.0.
            Installing System.Security.Cryptography.Primitives 4.0.0.
            Installing System.Threading.Timer 4.0.1.
            Installing System.Reflection.Primitives 4.0.1.
            Installing System.Diagnostics.Tracing 4.1.0.
            Installing System.Net.Primitives 4.3.0.
            Installing System.Net.Http 4.1.0.
            Installing System.Net.Primitives 4.0.11.
            Installing System.Security.Cryptography.X509Certificates 4.1.0.
            Installing System.IO.Compression 4.1.0.
            Installing System.Runtime.InteropServices 4.1.0.
            Installing runtime.native.System.Security.Cryptography 4.0.0.
            Installing Microsoft.NETCore.Targets 1.0.1.
            Installing System.Reflection.Emit 4.0.1.
            Installing System.Reflection.Emit.ILGeneration 4.0.1.
            Installing System.Reflection.TypeExtensions 4.1.0.
            Installing System.Reflection.Emit.Lightweight 4.0.1.
            Installing System.Threading.Tasks.Extensions 4.0.0.
            Installing Microsoft.NETCore.Windows.ApiSets 1.0.1.
            Installing Microsoft.NETCore.Jit 1.1.0.
            Installing Microsoft.NETCore.DotNetHostResolver 1.1.0.
            Installing Microsoft.CodeAnalysis.Common 1.3.0.
            Installing Microsoft.NETCore.Platforms 1.1.0.
            Installing System.AppContext 4.3.0.
            Installing System.IO.FileSystem 4.3.0.
            Installing System.Net.Sockets 4.3.0.
            Installing System.Console 4.3.0.
            Installing Microsoft.Win32.Primitives 4.3.0.
            Installing System.Diagnostics.Debug 4.3.0.
            Installing System.Linq 4.3.0.
            Installing System.Reflection 4.3.0.
            Installing System.Resources.ResourceManager 4.3.0.
            Installing System.Runtime.Handles 4.3.0.
            Installing System.Text.Encoding 4.3.0.
            Installing System.Threading.Timer 4.3.0.
            Installing System.IO.Compression.ZipFile 4.3.0.
            Installing System.Text.Encoding.Extensions 4.3.0.
            Installing System.Reflection.Primitives 4.3.0.
            Installing System.Runtime.InteropServices.RuntimeInformation 4.3.0.
            Installing System.Reflection.Extensions 4.3.0.
            Installing System.Xml.ReaderWriter 4.3.0.
            Installing System.Globalization.Calendars 4.3.0.
            Installing System.ObjectModel 4.3.0.
            Installing System.Diagnostics.Tools 4.3.0.
            Installing System.Diagnostics.Tracing 4.3.0.
            Installing System.Collections.Concurrent 4.3.0.
            Installing System.IO 4.3.0.
            Installing System.IO.FileSystem.Primitives 4.3.0.
            Installing System.Runtime.Numerics 4.3.0.
            Installing System.Xml.XDocument 4.3.0.
            Installing System.Text.RegularExpressions 4.3.0.
            Installing System.Collections 4.3.0.
            Installing System.Threading 4.3.0.
            Installing System.Runtime.InteropServices 4.3.0.
            Installing System.Globalization 4.3.0.
            Installing System.Security.Cryptography.Algorithms 4.2.1.
            Installing Microsoft.NETCore.Targets 1.0.5.
            Installing Microsoft.AspNetCore.Razor 1.0.4.
            Installing Microsoft.AspNetCore.Cryptography.Internal 1.0.5.
            Installing Microsoft.AspNetCore.DataProtection.Abstractions 1.0.5.
            Installing Microsoft.DotNet.InternalAbstractions 1.0.0.
            Installing System.Collections.Specialized 4.0.1.
            Installing Microsoft.Extensions.Logging.Debug 1.0.2.
            Installing Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.4.
            Installing Microsoft.AspNetCore.StaticFiles 1.0.5.
            Installing Microsoft.AspNetCore 1.0.8.
            Installing Microsoft.AspNetCore.Mvc 1.0.6.
            Installing Microsoft.NETCore.App 1.0.5.
            Installing Microsoft.Extensions.Logging.Abstractions 1.0.2.
            Installing System.Runtime.Loader 4.0.0.
            Installing Microsoft.Extensions.PlatformAbstractions 1.0.0.
            Installing Microsoft.Win32.Registry 4.0.0.
            Installing Microsoft.Extensions.FileProviders.Physical 1.0.1.
            Installing Microsoft.AspNetCore.Http.Abstractions 1.0.4.
            Installing Microsoft.Extensions.FileProviders.Abstractions 1.0.1.
            Installing Microsoft.Extensions.WebEncoders 1.0.3.
            Installing Microsoft.Extensions.Logging 1.0.2.
            Installing Microsoft.AspNetCore.Server.Kestrel 1.0.6.
            Installing Microsoft.AspNetCore.Routing 1.0.5.
            Installing Microsoft.Extensions.Configuration.FileExtensions 1.0.2.
            Installing Microsoft.Extensions.Logging.Console 1.0.2.
            Installing Microsoft.Extensions.Configuration.EnvironmentVariables 1.0.2.
            Installing Microsoft.Extensions.Configuration.Json 1.0.2.
            Installing Microsoft.AspNetCore.Hosting 1.0.5.
            Installing Microsoft.AspNetCore.Server.IISIntegration 1.0.6.
            Installing Microsoft.AspNetCore.Diagnostics 1.0.5.
            Installing Microsoft.Extensions.Options.ConfigurationExtensions 1.0.2.
            Installing Microsoft.AspNetCore.Mvc.TagHelpers 1.0.6.
            Installing Microsoft.Extensions.DependencyInjection 1.0.2.
            Installing Microsoft.Extensions.Caching.Memory 1.0.2.
            Installing Microsoft.AspNetCore.Mvc.Localization 1.0.6.
            Installing Microsoft.AspNetCore.Mvc.ApiExplorer 1.0.6.
            Installing Microsoft.AspNetCore.Mvc.Formatters.Json 1.0.6.
            Installing Microsoft.AspNetCore.Mvc.Cors 1.0.6.
            Installing Microsoft.AspNetCore.Mvc.DataAnnotations 1.0.6.
            Installing Microsoft.AspNetCore.Mvc.ViewFeatures 1.0.6.
            Installing Microsoft.AspNetCore.Mvc.Razor 1.0.6.
            Installing Microsoft.NETCore.Platforms 1.0.2.
            Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.7.
            Installing Microsoft.AspNetCore.Http.Extensions 1.0.4.
            Installing System.Collections.NonGeneric 4.0.1.
            Installing Microsoft.AspNetCore.Hosting.Abstractions 1.0.5.
            Installing runtime.native.System.Security.Cryptography 4.0.1.
            Installing System.Threading.ThreadPool 4.0.10.
            Installing System.ComponentModel 4.0.1.
            Installing System.Threading.Thread 4.0.0.
            Installing System.ComponentModel.Primitives 4.1.0.
            Installing runtime.native.System.Security.Cryptography 4.0.3.
            Installing Microsoft.NETCore.DotNetHost 1.0.1.
            Installing Microsoft.AspNetCore.Razor.Runtime 1.0.4.
            Installing System.Reflection.DispatchProxy 4.0.1.
            Installing Microsoft.AspNetCore.DataProtection 1.0.5.
            Installing Microsoft.Extensions.DependencyModel 1.0.0.
            Installing Microsoft.AspNetCore.Mvc.Abstractions 1.0.6.
            Installing System.Linq.Queryable 4.0.1.
            Installing System.ComponentModel.Annotations 4.1.0.
            Installing Microsoft.AspNetCore.Authorization 1.0.5.
            Installing System.Net.WebHeaderCollection 4.0.1.
            Installing System.Collections.Immutable 1.2.0.
            Installing System.Numerics.Vectors 4.1.1.
            Installing System.Resources.Reader 4.0.0.
            Installing System.Threading.Tasks.Parallel 4.0.1.
            Installing System.Threading.Tasks.Dataflow 4.6.0.
            Installing System.Linq.Parallel 4.0.1.
            Installing System.Net.Requests 4.0.11.
            Installing Microsoft.NETCore.DotNetHostPolicy 1.0.5.
            Installing System.Linq.Expressions 4.1.1.
            Installing System.IO.MemoryMappedFiles 4.0.0.
            Installing System.IO.UnmanagedMemoryStream 4.0.1.
            Installing System.IO.FileSystem.Watcher 4.0.0.
            Restore completed in 6.7 sec for /tmp/app/src/WebApplication/WebApplication.csproj.
            Installing System.Diagnostics.Process 4.1.0.
            Installing System.Net.NameResolution 4.0.0.
            Installing System.Reflection.Metadata 1.3.0.
            Installing System.Net.Security 4.0.1.
            Installing System.Net.Http 4.1.2.
            Installing Microsoft.VisualBasic 10.0.1.
            Installing Microsoft.Extensions.FileSystemGlobbing 1.0.1.
            Installing System.Text.Encodings.Web 4.0.1.
            Installing Microsoft.AspNetCore.Http.Features 1.0.4.
            Installing Microsoft.Extensions.Primitives 1.0.1.
            Installing Microsoft.Extensions.DependencyInjection.Abstractions 1.0.2.
            Installing Microsoft.Extensions.Options 1.0.2.
            Installing Microsoft.Extensions.Configuration.Abstractions 1.0.2.
            Installing Microsoft.AspNetCore.Hosting.Server.Abstractions 1.0.5.
            Installing Libuv 1.9.2.
            Installing Microsoft.Extensions.Localization.Abstractions 1.0.5.
            Installing Microsoft.Extensions.ObjectPool 1.0.1.
            Installing Microsoft.AspNetCore.Routing.Abstractions 1.0.5.
            Installing Microsoft.Net.Http.Headers 1.0.4.
            Installing Microsoft.Extensions.Configuration 1.0.2.
            Installing Microsoft.Extensions.Globalization.CultureInfoCache 1.0.5.
            Installing Microsoft.AspNetCore.Http 1.0.4.
            Installing Microsoft.AspNetCore.HttpOverrides 1.0.5.
            Installing System.ComponentModel.TypeConverter 4.1.0.
            Installing System.Security.Principal.Windows 4.0.0.
            Installing Microsoft.AspNetCore.Diagnostics.Abstractions 1.0.5.
            Installing Microsoft.AspNetCore.WebUtilities 1.0.4.
            Installing Microsoft.Extensions.Configuration.Binder 1.0.2.
            Installing Microsoft.Extensions.Caching.Abstractions 1.0.2.
            Installing Microsoft.AspNetCore.Localization 1.0.5.
            Installing Microsoft.AspNetCore.Mvc.Core 1.0.6.
            Installing Microsoft.AspNetCore.Cors 1.0.4.
            Installing Microsoft.Extensions.Localization 1.0.5.
            Installing Microsoft.AspNetCore.Html.Abstractions 1.0.3.
            Installing Microsoft.Extensions.FileProviders.Composite 1.0.1.
            Installing Microsoft.AspNetCore.Mvc.Razor.Host 1.0.6.
            Installing Microsoft.NETCore.Jit 1.0.7.
            Installing Microsoft.AspNetCore.Antiforgery 1.0.6.
            Installing Microsoft.NETCore.Targets 1.0.3.
            Installing Microsoft.NETCore.DotNetHostResolver 1.0.1.
            Installing System.Threading.Overlapped 4.0.1.
            Installing Microsoft.AspNetCore.JsonPatch 1.0.0.
            Installing runtime.native.System.Net.Security 4.0.1.
            Installing System.Security.Principal 4.0.1.
            Installing System.Net.WebSockets 4.0.0.
            Installing System.Security.Cryptography.X509Certificates 4.1.2.
            Installing System.Diagnostics.Contracts 4.0.1.
            Installing System.Security.Claims 4.0.1.
            Generating MSBuild file /tmp/app/src/WebApplication/obj/WebApplication.csproj.nuget.g.props.
            Generating MSBuild file /tmp/app/src/WebApplication/obj/WebApplication.csproj.nuget.g.targets.
            Restore completed in 7.33 sec for /tmp/app/src/WebApplication/WebApplication.csproj.
          Required dotnetframework versions: [1.0.5 1.1.0]
   -----> Installing dotnet-framework 1.0.5
          Download [https://buildpacks.cloudfoundry.org/dependencies/dotnet-framework/dotnet-framework.1.0.5.linux-amd64-1251a036.tar.xz]
          **WARNING** A newer version of dotnet-framework is available in this buildpack. Please adjust your app to use version 1.0.11 instead of version 1.0.5 as soon as possible. Old versions of dotnet-framework are only provided to assist in migrating to newer versions.
   -----> Installing dotnet-framework 1.1.0
          **ERROR** DEPENDENCY MISSING IN MANIFEST:

          Version 1.1.0 of dependency dotnet-framework is not supported by this buildpack.
          The versions of dotnet-framework supported in this buildpack are:
          	- 1.0.5
          	- 1.0.11
          	- 1.1.2
          	- 1.1.8
          	- 2.0.0
          	- 2.0.7
          	- 2.1.0
          	- 2.1.1

          **ERROR** Unable to install required dotnet frameworks: dependency dotnet-framework 1.1.0 not found
   Failed to compile droplet: Failed to run finalize script: exit status 12
   Exit status 223
```

**Comment by ameyer-pivotal** [comment] 2018-09-26 16:01
Hi @CleverChuk, I do recall we recently updated the logic that selects which version of the dotnet runtime (framework) to install. This issue seems to be resolved in the latest release. I was able to run your hello world app with `cf push -b https://github.com/cloudfoundry/dotnet-core-buildpack#v2.1.5`. I'll go ahead and close this, but feel free to re-open if you're still having issues.

**Closed by ameyer-pivotal** 2018-09-26 16:01 UTC
Labels: unscheduled
